# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'read_message_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MessageRead(object):
    def setupUi(self, MessageRead):
        MessageRead.setObjectName("MessageRead")
        MessageRead.resize(735, 830)
        self.gridLayout = QtWidgets.QGridLayout(MessageRead)
        self.gridLayout.setObjectName("gridLayout")
        self.message_text = QtWidgets.QTextBrowser(MessageRead)
        font = QtGui.QFont()
        font.setFamily("Segoe MDL2 Assets")
        font.setPointSize(12)
        self.message_text.setFont(font)
        self.message_text.setOpenExternalLinks(True)
        self.message_text.setObjectName("message_text")
        self.gridLayout.addWidget(self.message_text, 1, 0, 1, 1)
        self.Image = QtWidgets.QLabel(MessageRead)
        self.Image.setText("")
        self.Image.setObjectName("Image")
        self.gridLayout.addWidget(self.Image, 0, 0, 1, 1)

        self.retranslateUi(MessageRead)
        QtCore.QMetaObject.connectSlotsByName(MessageRead)

    def retranslateUi(self, MessageRead):
        _translate = QtCore.QCoreApplication.translate
        MessageRead.setWindowTitle(_translate("MessageRead", "Сообщение"))
